<div class="col-lg-12">
	<div class="row">
		<div class="row">
			<div class="section_header lead_name">
				<div class="pull-left"><span><?php echo $this->title; ?></span> </div>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
		</div>
		<div class="space10"></div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
		<!-- Start form open tag-->
		<?php
				$form = $this->form;
				echo $this->form()->openTag($form);
			    echo $this->formelement($form->get('id'));
			?>
        <div class="col-lg-12 col-md-12">
			<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 form-group">
				<?php echo $this->formLabel($form->get('fname')); ?>
				<?php echo $this->formelement($form->get('fname')); ?>
				<span class="error-msg"><?php echo $this->formElementErrors($form->get('fname')); ?></span>
			</div>
			<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 form-group">
			    <?php echo $this->formLabel($form->get('lname')); ?>
				<?php echo $this->formelement($form->get('lname')); ?>
				<span class="error-msg"><?php echo $this->formElementErrors($form->get('lname')); ?></span>
			</div>
			<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 form-group">
			    <?php echo $this->formLabel($form->get('email')); ?>
				<?php echo $this->formelement($form->get('email')); ?>
				<span class="error-msg"><?php echo $this->formElementErrors($form->get('email')); ?></span>
			</div>
			<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 form-group">
			    <?php echo $this->formLabel($form->get('password')); ?>
				<?php echo $this->formelement($form->get('password')); ?>
				<span class="error-msg"><?php echo $this->formElementErrors($form->get('password')); ?></span>
			</div>
			<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 form-group">
			    <?php echo $this->formLabel($form->get('mobile_no')); ?>
				<?php echo $this->formelement($form->get('mobile_no')); ?>
				<span class="error-msg"><?php echo $this->formElementErrors($form->get('mobile_no')); ?></span>
			</div>
			<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 form-group">
			    <?php echo $this->formLabel($form->get('address_line_1')); ?>
				<?php echo $this->formelement($form->get('address_line_1')); ?>
				<span class="error-msg"><?php echo $this->formElementErrors($form->get('address_line_1')); ?></span>
			</div>
			<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 form-group">
			    <?php echo $this->formLabel($form->get('address_line_2')); ?>
				<?php echo $this->formelement($form->get('address_line_2')); ?>
				<span class="error-msg"><?php echo $this->formElementErrors($form->get('address_line_2')); ?></span>
			</div>
			<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 form-group">
			    <?php echo $this->formLabel($form->get('status')); ?>
				<?php echo $this->formelement($form->get('status')); ?>
				<span class="error-msg"><?php echo $this->formElementErrors($form->get('status')); ?></span>
			</div>
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group" align="center">
				 <?php echo $this->formelement($form->get('submit')); ?>
				 <a href="../"><?php echo $this->formelement($form->get('cancel')); ?></a>
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
	
	
	
	
	
	