<div class="col-lg-12">
	<div class="row">
		<div class="row">
			<div class="section_header lead_name">
				<div class="pull-left"><span>User List</span> </div>
				<div class="pull-right">
				<a href="../user/create/">
					<input name="create" type="button" class="btn btn-lg btn-blue" value="Create">
				 </a>
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
		</div>
		<div class="space10"></div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-lg-12 col-md-12 ">
		<table id="list">
		<thead>
			<tr>
				<th>Full Name</th>
				<th>Email</th>
				<th>Contact No</th>
				<th>Address</th>
				<th>Status</th>
				<th>Created At</th>
				<th>Updated At</th>
				<th>Action</th>
			</tr>
			</thead>
			<tbody>
			<?php if(count($this->list) > 0) {
				foreach ($this->list as $key => $value) {
					echo "<tr>
						<td>{$value['name']}</td>
						<td>{$value['email']}</td>
						<td>{$value['mobile']}</td>
						<td width='20%'>{$value['address']}</td>
						<td>{$value['status']}</td>
						<td>{$value['createdAt']}</td>
						<td>{$value['updatedAt']}</td>
						<td>
							<a href='../user/update/{$value['id']}'>
								<input name='update' type='button' class='btn btn-xs btn-blue' value='Update'>
							</a>
							<a href='#' onclick='remove({$value['id']});return false;'>
								<input name='delete' type='button' class='btn btn-xs btn-danger' value='Delete'>
							</a>
						</td>
					</tr>";
			    }
			}else {
				echo '<tr><td collspan="'.count($this->list).'">No record found.</td></tr>';
			}?>
			</tbody>
           </table>
        </div>
	</div>

	<script type="text/javascript">
	function remove(id) {
		if(id) {
			const conf = confirm("Are you sure?");
			if(conf) {
				const url = '<?php echo $this->url; ?>remove/'+id;
				document.location = url;
			}
		} else {
			alert("Resource is invalid");
		}
		console.log(id);
	}
	</script>
	
	
	
	
	
	