<style>
    #page-wrapper {
        background-color: white;
    }
    .error-text {
        margin-top: 10px;
        margin-left: 100px;
        font-size: 24px;
        color: black;
    }
    #e-handler{
        display:none;
    }
</style>
<?php
/*
if (isset($message)) {
    ?>
    <div align="left">
        <span id="e-handler"><?php echo $message ?></span>
    </div>
    <?php
} else {*/

    ?>
    <?php if (isset($this->reason) && $this->reason): ?>
        <?php
        $reasonMessage = '';
        $imgSrc='';
        switch ($this->reason) {
            case 'error-controller-cannot-dispatch':
                $reasonMessage = $this->translate('Access Denied. Please contact to adminstrator.');
                $imgSrc='';
                break;
            case 'error-controller-not-found':
                $reasonMessage = $this->translate('The requested controller could not be mapped to an existing controller class.');
                break;
            case 'error-controller-invalid':
                $reasonMessage = $this->translate('The requested controller was not dispatchable.');
                break;
            case 'error-router-no-match':
                $reasonMessage = $this->translate('The requested URL could not be matched by routing.');
                break;
            default:
                $reasonMessage = $this->translate('We cannot determine at this time why a 404 was generated.');
                break;
        }
        ?>
        <div align="left">
            <?php if(!empty($imgSrc)){ ?>
            <img src="<?php echo $this->basePath(filePath . '/img/not-found.jpg') ?>">
            <?php } ?>
            <p class="error-text"><?php echo $reasonMessage ?></p>
            <pre style="color:red;display: none;" class="error-handler"></pre>
        </div>


    <?php endif ?>

    <?php if (isset($this->controller) && $this->controller): ?>

        <dl>
            <dt><?php //echo $this->translate('Controller'); ?></dt>
            <dd><?php //echo $this->escapeHtml($this->controller); ?>
        <?php
        if (isset($this->controller_class) && $this->controller_class && $this->controller_class != $this->controller
        ) {
            //echo '(' . sprintf($this->translate('resolves to %s'), $this->escapeHtml($this->controller_class)) . ')';
            ?>
                    <pre style="color:red;" class="error-handler"></pre>
                    <?php
                }
                ?>
            </dd>
        </dl>
                <?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

            <?php if (isset($this->exception) && $this->exception instanceof Exception): ?>
                <pre style="color:red;"><?php echo $this->escapeHtml($this->exception->getMessage()) ?></pre>
                <pre style="color:red;" class="error-handler"></pre>
            <?php else: ?>

                <h3><?php //echo $this->translate('No Exception available') ?></h3>

            <?php endif ?>

        <?php endif
        ?>
        <?php
    endif;
//}
?>

<script>
    $(document).ready(function () {
        var text_data = $('#e-handler').text();
        $('.error-handler').text(text_data);
    })

</script>