<?php
if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath() . '/public');
}
?>
<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Saber Tech :: Admin')->setSeparator(' - ')->setAutoEscape(false); ?>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
                ->prependStylesheet($this->basePath(FILE_PATh . '/css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath(FILE_PATh . '/css/morris.css'))
                ->prependStylesheet($this->basePath(FILE_PATh . '/css/sb-admin-2.css'))
                ->prependStylesheet($this->basePath(FILE_PATh . '/css/metisMenu.min.css'))
                ->prependStylesheet($this->basePath(FILE_PATh . '/css/bootstrap.min.css'))
        ?>
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath(FILE_PATh . '/js/sb-admin-2.js'))
                ->prependFile($this->basePath(FILE_PATh . '/js/metisMenu.min.js'))
                ->prependFile($this->basePath(FILE_PATh . '/js/bootstrap.min.js'))
                ->prependFile($this->basePath(FILE_PATh . '/js/jquery.min.js'))
                ->prependFile($this->basePath(FILE_PATh . '/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath(FILE_PATh . '/js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>
    </head>
    <body>
        <div class="container">
             <?php echo $this->content; ?>
        </div>
    </body>
</html>
