<div class="col-lg-12">
	<div class="row">
		<div class="row">
			<div class="section_header lead_name">
				<div class="pull-left"><span>Dashboard</span> </div>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
		</div>
		<div class="space10"></div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-lg-12 col-md-12 ">Please use the MENU to browse through different sections.</div>
	</div>
	
	
	
	
	
	